// AgentRoom 开发用 mock 数据
// 真实数据接入时：service.ts 把这部分逻辑替换为实际 API 调用
// DESIGN.md §13 的 10 个官方模板在此落地

import type { Room, Member, Message, RoomTemplate, RoomMetrics, InterventionEvent } from './types';

// ── 10 个官方模板（§13） ──

export const ROOM_TEMPLATES: RoomTemplate[] = [
  {
    id: 'ecom_cs3',
    name: '电商客服三人组',
    tagline: '主客服 + 投诉专员 + 售后专员，反应式 + 投影企业微信',
    category: 'ops',
    icon: 'support_agent',
    gradient: 'from-[#FF6B6B] to-[#FFA06B]',
    stars: 1247,
    memberCount: 3,
    defaultPolicy: 'reactive',
    supportsProjection: true,
    budgetCNY: 10,
    initialPromptHint: '简单描述你的店铺或要接待的场景...',
    initialFacts: { '店铺名': '—', '品类': '—', '退换货政策': '7 天无理由' },
    members: [
      { roleId: 'lead', role: '主客服', emoji: '🧑‍💼', isModerator: true, model: 'claude-haiku-4' },
      { roleId: 'complaint', role: '投诉专员', emoji: '🧏', model: 'claude-haiku-4' },
      { roleId: 'after_sales', role: '售后专员', emoji: '🧑‍🔧', model: 'claude-haiku-4' },
    ],
  },
  {
    id: 'community_ops',
    name: '社群运营三件套',
    tagline: '欢迎官 / FAQ 官 / 敏感词监控，投影 TG/Discord',
    category: 'ops',
    icon: 'groups',
    gradient: 'from-[#4ECDC4] to-[#44A3FF]',
    stars: 892,
    memberCount: 3,
    defaultPolicy: 'reactive',
    supportsProjection: true,
    budgetCNY: 8,
    members: [
      { roleId: 'greeter', role: '欢迎官', emoji: '👋', model: 'deepseek-v3.5' },
      { roleId: 'faq', role: 'FAQ 官', emoji: '📚', model: 'deepseek-v3.5' },
      { roleId: 'moderator', role: '敏感词监控', emoji: '🛡️', model: 'deepseek-v3.5' },
    ],
  },
  {
    id: 'content_studio',
    name: '内容工作室（流水线）',
    tagline: '选题 → 写稿 → 配图 → 校对',
    category: 'ops',
    icon: 'edit_note',
    gradient: 'from-[#B24BF3] to-[#667EEA]',
    stars: 756,
    memberCount: 4,
    defaultPolicy: 'roundRobin',
    supportsProjection: false,
    budgetCNY: 15,
    initialWhiteboard: '# 草稿\n\n（各成员按顺序在此协作）',
    members: [
      { roleId: 'topic', role: '选题官', emoji: '🔍', model: 'claude-opus-4' },
      { roleId: 'writer', role: '主笔', emoji: '✍️', model: 'claude-opus-4' },
      { roleId: 'illustrator', role: '配图官', emoji: '🎨', model: 'claude-opus-4' },
      { roleId: 'editor', role: '校对', emoji: '🔎', model: 'claude-haiku-4' },
    ],
  },
  {
    id: 'presale_aftersale',
    name: '售前售后双 Agent',
    tagline: '主持人 Agent 按意图分流',
    category: 'ops',
    icon: 'contact_support',
    gradient: 'from-[#F093FB] to-[#F5576C]',
    stars: 432,
    memberCount: 3,
    defaultPolicy: 'moderator',
    supportsProjection: true,
    budgetCNY: 10,
    members: [
      { roleId: 'dispatcher', role: '分流员', emoji: '🎩', isModerator: true, model: 'claude-haiku-4' },
      { roleId: 'presale', role: '售前', emoji: '🧑‍💻', model: 'claude-haiku-4' },
      { roleId: 'aftersale', role: '售后', emoji: '🧑‍🔧', model: 'claude-haiku-4' },
    ],
  },
  {
    id: 'code_review',
    name: '代码评审 PR 小组',
    tagline: 'Planner / Coder / Reviewer / Security，轮流 + 沙箱',
    category: 'dev',
    icon: 'code',
    gradient: 'from-[#11998E] to-[#38EF7D]',
    stars: 1089,
    memberCount: 4,
    defaultPolicy: 'roundRobin',
    supportsProjection: false,
    budgetCNY: 20,
    initialPromptHint: '粘贴 PR 链接或 diff 片段...',
    members: [
      { roleId: 'planner', role: 'Planner', emoji: '🗺️', model: 'claude-opus-4' },
      { roleId: 'coder', role: 'Coder', emoji: '👨‍💻', model: 'claude-opus-4' },
      { roleId: 'reviewer', role: 'Reviewer', emoji: '🔍', model: 'claude-opus-4' },
      { roleId: 'security', role: 'Security', emoji: '🛡️', model: 'claude-haiku-4' },
    ],
  },
  {
    id: 'arch_review',
    name: '架构设计会议',
    tagline: 'PM / 架构师 / 测试 / UX',
    category: 'dev',
    icon: 'architecture',
    gradient: 'from-[#667EEA] to-[#764BA2]',
    stars: 678,
    memberCount: 4,
    defaultPolicy: 'reactive',
    supportsProjection: false,
    budgetCNY: 15,
    initialPromptHint: '描述你要评审的需求或技术方案...',
    members: [
      { roleId: 'pm', role: '产品经理', emoji: '🎩', isModerator: true, model: 'claude-opus-4' },
      { roleId: 'arch', role: '架构师', emoji: '🏗️', model: 'claude-opus-4' },
      { roleId: 'qa', role: '测试', emoji: '🧪', model: 'claude-haiku-4' },
      { roleId: 'ux', role: 'UX', emoji: '🎨', model: 'claude-haiku-4' },
    ],
  },
  {
    id: 'multi_model_debate',
    name: '多模型辩论',
    tagline: 'GPT-5 vs Claude vs DeepSeek vs Gemini，竞价发言',
    category: 'research',
    icon: 'forum',
    gradient: 'from-[#FC466B] to-[#3F5EFB]',
    stars: 2341,
    memberCount: 4,
    defaultPolicy: 'bidding',
    supportsProjection: false,
    budgetCNY: 25,
    initialPromptHint: '给 4 个 AI 一个辩题（例如：程序员 5 年内会失业吗？）',
    members: [
      { roleId: 'gpt', role: 'GPT-5', emoji: '🟢', model: 'gpt-5' },
      { roleId: 'claude', role: 'Claude Opus', emoji: '🟠', model: 'claude-opus-4' },
      { roleId: 'ds', role: 'DeepSeek V3.5', emoji: '🔷', model: 'deepseek-v3.5' },
      { roleId: 'gemini', role: 'Gemini 2.5 Pro', emoji: '💠', model: 'gemini-2.5-pro' },
    ],
  },
  {
    id: 'red_blue_team',
    name: '红蓝对抗（安全）',
    tagline: '红队×2 攻击 + 蓝队×2 防御 + 裁判',
    category: 'research',
    icon: 'security',
    gradient: 'from-[#EB3349] to-[#F45C43]',
    stars: 512,
    memberCount: 5,
    defaultPolicy: 'roundRobin',
    supportsProjection: false,
    budgetCNY: 18,
    members: [
      { roleId: 'red1', role: '红队·侦察', emoji: '🔴', model: 'claude-opus-4' },
      { roleId: 'red2', role: '红队·突破', emoji: '🔴', model: 'claude-opus-4' },
      { roleId: 'blue1', role: '蓝队·检测', emoji: '🔵', model: 'claude-opus-4' },
      { roleId: 'blue2', role: '蓝队·响应', emoji: '🔵', model: 'claude-opus-4' },
      { roleId: 'judge', role: '裁判', emoji: '⚖️', isModerator: true, model: 'claude-haiku-4' },
    ],
  },
  {
    id: 'socratic',
    name: '苏格拉底哲学对话',
    tagline: '苏格拉底 + 提问者 + 记录员',
    category: 'fun',
    icon: 'psychology',
    gradient: 'from-[#DA22FF] to-[#9733EE]',
    stars: 321,
    memberCount: 3,
    defaultPolicy: 'moderator',
    supportsProjection: false,
    budgetCNY: 10,
    initialPromptHint: '你想和苏格拉底讨论什么问题？',
    members: [
      { roleId: 'socrates', role: '苏格拉底', emoji: '🏛️', isModerator: true, model: 'claude-opus-4' },
      { roleId: 'inquirer', role: '提问者', emoji: '🤔', model: 'claude-haiku-4' },
      { roleId: 'scribe', role: '记录员', emoji: '📜', model: 'claude-haiku-4' },
    ],
  },
  {
    id: 'english_coach',
    name: '英语口语陪练',
    tagline: '老师 + 陪练同学 + 语法纠音评委，支持 TTS/STT',
    category: 'fun',
    icon: 'translate',
    gradient: 'from-[#F7971E] to-[#FFD200]',
    stars: 876,
    memberCount: 3,
    defaultPolicy: 'roundRobin',
    supportsProjection: false,
    budgetCNY: 12,
    members: [
      { roleId: 'teacher', role: 'Teacher', emoji: '🧑‍🏫', isModerator: true, model: 'claude-opus-4' },
      { roleId: 'peer', role: 'Peer', emoji: '🧑‍🎓', model: 'claude-haiku-4' },
      { roleId: 'critic', role: 'Grammar Critic', emoji: '✅', model: 'claude-haiku-4' },
    ],
  },
];

// ── 演示房间（启动时提供 1 个 demo）──

const NOW = Date.now();

export const DEMO_MEMBERS: Member[] = [
  {
    id: 'm_pm',
    roomId: 'room_demo',
    kind: 'agent',
    name: '产品经理',
    role: 'PM',
    emoji: '🎩',
    model: 'claude-opus-4',
    tokenUsage: 1240,
    costCNY: 0.34,
    status: 'thinking',
    isModerator: true,
    createdAt: NOW - 600_000,
  },
  {
    id: 'm_arch',
    roomId: 'room_demo',
    kind: 'agent',
    name: '架构师',
    role: '架构师',
    emoji: '🏗️',
    model: 'claude-opus-4',
    tokenUsage: 890,
    costCNY: 0.28,
    status: 'idle',
    createdAt: NOW - 600_000,
  },
  {
    id: 'm_qa',
    roomId: 'room_demo',
    kind: 'agent',
    name: '测试',
    role: 'QA',
    emoji: '🧪',
    model: 'claude-haiku-4',
    tokenUsage: 520,
    costCNY: 0.12,
    status: 'idle',
    createdAt: NOW - 600_000,
  },
  {
    id: 'm_ux',
    roomId: 'room_demo',
    kind: 'agent',
    name: 'UX',
    role: 'UX',
    emoji: '🎨',
    model: 'claude-haiku-4',
    tokenUsage: 410,
    costCNY: 0.09,
    status: 'idle',
    createdAt: NOW - 600_000,
  },
  {
    id: 'm_you',
    roomId: 'room_demo',
    kind: 'human',
    name: 'You',
    role: 'Owner',
    emoji: '🧑',
    tokenUsage: 0,
    costCNY: 0,
    status: 'idle',
    createdAt: NOW - 600_000,
  },
];

export const DEMO_ROOM: Room = {
  id: 'room_demo',
  title: '产品评审会 · 批量导入用户标签',
  state: 'active',
  policy: 'reactive',
  strictApproval: false,
  createdAt: NOW - 600_000,
  updatedAt: NOW - 1000,
  budget: {
    limitCNY: 10,
    usedCNY: 3.42,
    tokensUsed: 3060,
    warnAt: 0.7,
    hardStopAt: 1.0,
  },
  memberIds: ['m_pm', 'm_arch', 'm_qa', 'm_ux', 'm_you'],
  moderatorId: 'm_pm',
  facts: [
    { key: '规模', value: '50 万用户', authorId: 'm_pm', updatedAt: NOW - 500_000 },
    { key: 'QPS 峰值', value: '2000', authorId: 'm_arch', updatedAt: NOW - 400_000 },
    { key: '预算', value: '¥10', authorId: 'm_you', updatedAt: NOW - 600_000 },
    { key: '交付日期', value: '2026-05-15', authorId: 'm_pm', updatedAt: NOW - 300_000 },
  ],
  whiteboard: `# 技术方案 A\n\n- 读写分离\n- Redis 缓存层\n- 批量导入走 Kafka 异步处理\n\n## 风险\n- 数据一致性\n- 冷启动 2 分钟\n\n## TODO\n- [ ] 压测\n- [ ] 容灾切换演练`,
  tasks: [
    { id: 't1', text: '跑压测（1000 req/s × 10 min）', assigneeId: 'm_qa', creatorId: 'm_pm', status: 'doing', dueAt: NOW + 1800_000, createdAt: NOW - 200_000 },
    { id: 't2', text: '调整入口位置到首页', assigneeId: 'm_ux', creatorId: 'm_pm', status: 'todo', createdAt: NOW - 180_000 },
    { id: 't3', text: '定义 REST API 契约', assigneeId: 'm_arch', creatorId: 'm_pm', status: 'done', createdAt: NOW - 400_000, completedAt: NOW - 60_000 },
  ],
  locker: [
    { id: 'f1', name: 'mockup.png', size: 234_000, mime: 'image/png', kind: 'image', uploaderId: 'm_you', createdAt: NOW - 120_000 },
  ],
};

// ── 演示消息流（给 UI 一个"有内容"的首印象）──

export const DEMO_MESSAGES: Message[] = [
  {
    id: 'msg1',
    roomId: 'room_demo',
    authorId: 'm_pm',
    kind: 'chat',
    content: '大家好，今天评审一个新需求：**批量导入用户标签**，预计 50 万用户，峰值 QPS 2000，本周五交付。',
    tokensIn: 40, tokensOut: 58,
    costCNY: 0.04,
    model: 'claude-opus-4',
    timestamp: NOW - 540_000,
    mentionIds: [],
  },
  {
    id: 'msg2',
    roomId: 'room_demo',
    authorId: 'm_arch',
    kind: 'chat',
    content: '量级可以，我倾向于**读写分离 + Kafka 异步导入**。让我先跑个压测看看。',
    tokensIn: 120, tokensOut: 46,
    costCNY: 0.05,
    model: 'claude-opus-4',
    timestamp: NOW - 480_000,
  },
  {
    id: 'msg3',
    roomId: 'room_demo',
    authorId: 'm_qa',
    kind: 'tool',
    content: '',
    toolName: 'benchmark.run',
    toolArgs: { target: 'import_tags', concurrency: 1000, duration: '60s' },
    toolStatus: 'success',
    toolResult: 'p50=45ms p95=112ms p99=238ms error_rate=0.02%',
    tokensIn: 80, tokensOut: 22,
    costCNY: 0.02,
    model: 'claude-haiku-4',
    timestamp: NOW - 420_000,
  },
  {
    id: 'msg4',
    roomId: 'room_demo',
    authorId: 'm_qa',
    kind: 'chat',
    content: '压测跑出来了：p99 ≈ 238ms，错误率 0.02%。如果要把 p99 压到 100ms，建议加一层 Redis 缓存。',
    tokensIn: 140, tokensOut: 52,
    costCNY: 0.05,
    model: 'claude-haiku-4',
    timestamp: NOW - 360_000,
    referenceMessageId: 'msg3',
  },
  {
    id: 'msg5',
    roomId: 'room_demo',
    authorId: 'm_ux',
    kind: 'chat',
    content: '我看了 @架构师 的方案，想反馈一点：**导入入口目前藏在"设置 → 高级 → 批量操作"**，用户基本找不到。建议前置到用户管理首页。',
    tokensIn: 180, tokensOut: 68,
    costCNY: 0.06,
    model: 'claude-haiku-4',
    timestamp: NOW - 300_000,
    mentionIds: ['m_arch'],
    reactions: [{ emoji: '👍', byMemberIds: ['m_pm', 'm_you'] }],
  },
  {
    id: 'msg6',
    roomId: 'room_demo',
    authorId: 'm_you',
    kind: 'chat',
    content: '先搁置 UX 问题，聚焦后端。@架构师 Kafka 方案冷启动是不是 2 分钟太久？',
    timestamp: NOW - 240_000,
    mentionIds: ['m_arch'],
  },
  {
    id: 'msg7',
    roomId: 'room_demo',
    authorId: 'm_arch',
    kind: 'thinking',
    content: '',
    streaming: true,
    timestamp: NOW - 180_000,
  },
  {
    id: 'msg8',
    roomId: 'room_demo',
    authorId: 'm_pm',
    kind: 'whisper',
    whisperTargetIds: ['m_you'],
    content: '（私聊）Boss，UX 的反馈其实挺关键，但架构师有点抵触，我等下用"风险"话术再提一次。',
    tokensIn: 60, tokensOut: 38,
    costCNY: 0.02,
    model: 'claude-opus-4',
    timestamp: NOW - 120_000,
  },
];

// ── 行为指标演示数据 ──

export const DEMO_METRICS: RoomMetrics = {
  agreementScore: 0.62,
  infoGainTrend: 'up',
  dominanceGini: 0.34,
  convergenceRounds: null,
  toolUsageRate: 0.18,
  totalMessages: DEMO_MESSAGES.length,
  totalTokens: 3060,
  perMember: [
    { memberId: 'm_pm', messages: 2, tokens: 1240, costCNY: 0.34 },
    { memberId: 'm_arch', messages: 2, tokens: 890, costCNY: 0.28 },
    { memberId: 'm_qa', messages: 2, tokens: 520, costCNY: 0.12 },
    { memberId: 'm_ux', messages: 1, tokens: 410, costCNY: 0.09 },
    { memberId: 'm_you', messages: 1, tokens: 0, costCNY: 0 },
  ],
};

export const DEMO_INTERVENTIONS: InterventionEvent[] = [
  { id: 'iv1', roomId: 'room_demo', at: NOW - 240_000, level: 1, byHumanId: 'm_you', label: '人类发言' },
];

// ── 工具：构造空白房间 ──

export function buildEmptyRoom(id: string, title: string, memberIds: string[]): Room {
  return {
    id,
    title,
    state: 'draft',
    policy: 'reactive',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    budget: { limitCNY: 10, usedCNY: 0, tokensUsed: 0, warnAt: 0.7, hardStopAt: 1.0 },
    memberIds,
    facts: [],
    whiteboard: '',
    tasks: [],
    locker: [],
  };
}
